service: nest-separator

plugins:
  - serverless-offline
provider:
  name: aws
  runtime: nodejs18.x
functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          path: /{any+}
          method: any
